apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  entrypoint: diamond
  templates:
    - name: diamond
      dag:
        tasks:
          - name: wait-sync
            suspend:
              duration: 5s
          - name: B
            dependencies: [wait-sync]
            template: k6-test-info-apis
          - name: C
            dependencies: [wait-sync]
            template: k6-test-info-apis
          - name: D
            dependencies: [wait-sync]
            template: k6-test-info-apis
    - name: k6-test-merchant-apis
      container:
        image: loadimpact/k6
        imagePullPolicy: IfNotPresent
        args:
          - run
          #          - -eHOST=https://lcp-settle-api.line-apps-beta.com
          - /k6-scripts/test-merchant-apis.js
        volumeMounts:
          - name: k6-scripts
            mountPath: /k6-scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts
            items:
              - key: 'test-merchant-apis.js'
                path: 'test-merchant-apis.js'
    - name: k6-test-info-apis
      container:
        image: loadimpact/k6
        imagePullPolicy: IfNotPresent
        args:
          - run
          #          - -eHOST=https://lcp-settle-api.line-apps-beta.com
          - /k6-scripts/test-info-apis.js
        volumeMounts:
          - name: k6-scripts
            mountPath: /k6-scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts
            items:
              - key: 'test-info-apis.js'
                path: 'test-info-apis.js'