apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  generateName: hello-world
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        steps:
          - - name: hello1            # hello1 is run before the following steps
              template: whalesay2
    - name: whalesay2
      container:
        image: alpine:3.16
        command: [ "sleep", "10" ]
#        resources:
#          limits:
#            memory: 32Mi
#            cpu: 100m