apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: steps
spec:
  entrypoint: hello-hello-hello

  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
    - name: hello-hello-hello
      # Instead of just running a container
      # This template has a sequence of steps
      steps:
        - - name: hello1            # hello1 is run before the following steps
            template: whalesay
        - - name: hello2a           # double dash => run after previous step
            template: whalesay
          - name: hello2b           # single dash => run in parallel with previous step
            template: whalesay

    # This is the same template as from the previous example
    - name: whalesay
      container:
        image: alpine:latest
        command: ["sleep", "10"]