apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  generateName: hello-world
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      steps:
        - - name: hello1            # hello1 is run before the following steps
            template: k6-test-merchant-apis
#        - - name: hello2           # hello1 is run before the following steps
#            template: k6-test-info-apis
#        - - name: hello3           # hello1 is run before the following steps
#            template: whalesay2
    - name: k6-test-merchant-apis
      container:
        image: loadimpact/k6
        imagePullPolicy: IfNotPresent
        args:
          - run
          - /k6-scripts/test-merchant-apis.js
        volumeMounts:
          - name: k6-scripts
            mountPath: /k6-scripts
#      volumes:
#        - name: k6-scripts
#          configMap:
#            name: k6-scripts
#            items:
#              - key: 'test-merchant-apis.js'
#                path: 'test-merchant-apis.js'
#    - name: k6-test-merchant-apis
#      containers:
#        image: loadimpact/k6
  #          imagePullPolicy: IfNotPresent
#        args:
#          - run
#          - /k6-scripts/test-merchant-apis.js
#        volumeMounts:
#          - name: k6-scripts
#            mountPath: /k6-scripts
#        volumes:
#          - name: k6-scripts
#            configMap:
#              name: k6-scripts
#              items:
#                - key: 'test-merchant-apis.js'
#                  path: 'test-merchant-apis.js'
#    - name: k6-test-info-apis
#      containers:
#        image: loadimpact/k6
#        imagePullPolicy: IfNotPresent
#        args:
#          - run
#          - /k6-scripts/test-info-apis.js
#        volumeMounts:
#          - name: k6-scripts
#            mountPath: /k6-scripts
#        volumes:
#          - name: k6-scripts
#            configMap:
#              name: k6-scripts
#              items:
#                - key: 'test-info-apis.js'
#                  path: 'test-info-apis.js'