apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  entrypoint: guestbook-ui
  templates:
    - name: argo-workflow
      dag:
        tasks:
          - name: guestbook-ui
            template: guestbook-ui
    - name: guestbook-ui
      container:
        image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        ports:
          - containerPort: 8090