apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - workflow-map.yaml

resources:
#  - job-integration-testing.yaml
#  - argo-role.yaml
#  - pre-sync-job.yaml
#  - argo-workflow.yaml
#  - common.yaml
  - argo-dag.yaml

configMapGenerator:
  - name: k6-scripts
    files:
      - test-merchant-apis.js
      - test-payment-fee-apis.js
      - test-settlement-policy-apis.js
      - upload-report.js
      - aws.min.js.map
      - aws.min.js
  - name: lcp-settle-api-env
    literals:
      - SPRING_PROFILES_ACTIVE=beta
      - LCP_SETTLE_TOKEN=_Ed6edFW27*MB!BR.3ghJbHT2ZpBcj3vKW.WNj49Ao-NBe2WMHr
      - MYSQL_URL=jdbc:mysql://lcp-settle.verda-lcp-settle.jp2-dev.db.line-apps-dev.com:20306/lcp_settle?characterEncoding=utf-8&serverTimezone=UTC
      - MYSQL_USERNAME=lcp_settle_dev
      - MYSQL_PASSWORD=W_2vyC.F8pTHa2rWocU.
      - LCP_SETTLE_CORS=http://localhost:3000,https://lcp-settle.beta-sentinel.linecorp.com,https://lcp-settle-oca.line-apps-beta.com
      - DEFAULT_SERVICE_CHANNEL=MP_TW
      - BASE_FEE=0.02
      - INSTALLMENT3_FEE=0.025
      - INSTALLMENT6_FEE=0.034
      - INSTALLMENT12_FEE=0.067
      - INSTALLMENT18_FEE=0.09
      - INSTALLMENT24_FEE=0.12
      - LINE_PAY_FEE=0.02
      - ATM_FEE=0.01
      - NEWEB_PAY_PAYMENT_METHOD=CREDIT_CARD,CREDIT_CARD_INSTALLMENT_3,CREDIT_CARD_INSTALLMENT_6,CREDIT_CARD_INSTALLMENT_12,CREDIT_CARD_INSTALLMENT_18,CREDIT_CARD_INSTALLMENT_24
      - LINE_PAY_PAYMENT_METHOD=LINE_PAY
      - CVS_BARCODE_FEE=0.01
      - DEFAULT_FEE=0.02
      - CLIENT_TIMEOUT=60
      - RETRY_TIMES=3
      - LCPPG_ENDPOINT=https://lcp-pg-api.line-apps-beta.com
      - LCPPG_AUTH=eyAgInR5cCI6ICJKV1QiLCAgImFsZyI6ICJIUzI1NiJ9.eyAgImlzcyI6ICJMSU5FU1BNIiwgICJzZXJ2aWNlX2lkIjogIk1QX1RXIiwgICJvcGVyYXRvcl9pZCI6ICJMQ1BfU0VUVExFIn0.EQUbd_ONLyAbnmTu7yxEPHw_dYGOq7BZalneZOth7yM
      - SERVICE_ID=MP_TW
      - STARTUP_CONSUMER=true
      - KAFKA_RETRY=3
      - KAFKA_SLEEP_SECOND=1
      - LCP_SETTLE_KAFKA_CONSUMER_GROUP_ID=beta-lcp-settle-api
      - KAFKA_CONSUMER_MAX_POLL_RECORDS=100
      - KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS=600000
      - KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS=200000
      - KAFKA_CONSUMER_SESSION_TIMEOUT_MS=1200000
      - KAFKA_CONSUMER_FETCH_MIN_BYTES=1
      - KAFKA_CONSUMER_FETCH_MAX_BYTES=157286400
      - KAFKA_CONSUMER_MAX_WAIT_MS=100
      - KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=1048576
      - KAFKA_PRODUCER_RETRIES=2147483647
      - KAFKA_PRODUCER_LINGER_MS=100
      - KAFKA_PRODUCER_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION=5
      - KAFKA_PRODUCER_ENABLE_IDEMPOTENCE=true
      - KAFKA_PRODUCER_TRANSACTION_TIMEOUT_MS=300000
      - KAFKA_PRODUCER_BATCH_SIZE=16384
      - KAFKA_PRODUCER_COMPRESSION_TYPE=gzip
      - KAFKA_PRODUCER_REQUEST_TIMEOUT_MS=600000
      - KAFKA_PRODUCER_DELIVERY_TIMEOUT_MS=1200000
      - KAFKA_TOPIC_SET_FEE=lcp-settle-setfee-v1
      - KAFKA_TOPIC_CANCEL_FEE=lcp-settle-cancelfee-v1
      - KAFKA_JKS_LOCATION=file:/opt/lcp-settle-api/certificates/beta-imf-kafka-client.truststore.jks
      - KAFKA_JKS_PASSWORD=imf-client
      - KAFKA_BOOTSTRAP_SERVERS=kf01-vdajp-imf.linecorp-dev.com:11498,kf02-vdajp-imf.linecorp-dev.com:11498,kf03-vdajp-imf.linecorp-dev.com:11498
      - KAFKA_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="lcp-settle-27602eacef564a0995ec9413589be96f" password="BT3OY8kvhggL";
      - name: lcp-settle-oca-env
        literals:
          - NEXT_PUBLIC_API_URL=https://lcp-settle-api.line-apps-beta.com
          - NEXT_PUBLIC_API_KEY=_Ed6edFW27*MB!BR.3ghJbHT2ZpBcj3vKW.WNj49Ao-NBe2WMHr
          - NEXT_PUBLIC_PERMISSION=tw_ec_exam,tw_ec_developer,lcp_admin,lcp_qa
          - NEXT_PUBLIC_SELLERDOMAIN=https://oca-admin.beta-sentinel.linecorp.com
          - NEXT_PUBLIC_SERVICE_CHANNEL_CODE=MP_TW
