apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - workflow-map.yaml

resources:
#  - job-integration-testing.yaml
#  - argo-role.yaml
#  - pre-sync-job.yaml
#  - argo-workflow.yaml
  - pvc.yaml
  - hostpath.yaml
#  - argo-dag.yaml

configMapGenerator:
  - name: k6-scripts
    files:
      - test-merchant-apis.js
      - test-payment-fee-apis.js
      - test-settlement-policy-apis.js
      - upload-report.js
      - aws.min.js.map
      - aws.min.js
