apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - job-integration-testing.yaml
#  - argo-role.yaml
  - pre-sync-job.yaml
  - argo-workflow.yaml
  - git::https://git.linecorp.com/tw-sre/serve-common.git//configurations/?ref=1.1.2

#configMapGenerator:
#  - name: k6-scripts
#    files:
#      - test-merchant-apis.js