apiVersion: v1
kind: Pod
metadata:
  name: vol1
spec:
  containers:
    - image: alpine:3.16
      name: vm1
      command: ["sleep", "10m"]
#      args:
#        - run
#        - /k6-scripts/html/test-merchant-apis.js
      volumeMounts:
        - mountPath: /k6-scripts
          name: cache-volume
        - mountPath: /
          name: k6-scripts
          subPath: k6-scripts
    - name: vm2
      image: nginx
#      volumeMounts:
#        - mountPath: /usr/share/nginx/html
#          name: cache-volume
      volumeMounts:
        - mountPath: /k6-scripts
          name: cache-volume
  volumes:
    - name: cache-volume
      hostPath:
        # 宿主上目录位置
        path: /
        # 此字段为可选
        type: Directory
    - name: k6-scripts
      configMap:
        name: k6-scripts
        items:
          - key: 'test-merchant-apis.js'
            path: 'test-merchant-apis.js'
#  volumes:
#    - name: cache-volume
#      emptyDir:
#        medium: Memory
#        sizeLimit: 100Mi

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: test-volume
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: my-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /k6-scripts