apiVersion: v1
kind: Pod
metadata:
  name: vol1
spec:
  initContainers:
    - name: create-empty-file
      image: alpine:3.16
      command: [ "touch", "/empty_file" ]
      volumeMounts:
        - mountPath: /k6-scripts
          name: k6-scripts
  containers:
    - image: alpine:3.16
      name: vm1
      command: ["sleep", "10m"]
#      args:
#        - run
#        - /k6-scripts/html/test-merchant-apis.js
      envFrom:
        - configMapRef:
            name: k6-scripts
      volumeMounts:
        - mountPath: /k6-scripts
          name: cache-volume
#        - mountPath: /usr/share/k6-scripts
#          name: k6-scripts
#          subPath: k6-scripts
    - name: vm2
      image: nginx
#      volumeMounts:
#        - mountPath: /usr/share/nginx/html
#          name: cache-volume
      volumeMounts:
        - mountPath: /usr/share/k6-scripts
          name: cache-volume
  volumes:
    - name: cache-volume
      persistentVolumeClaim:
        claimName: test-volume
    - name: k6-scripts
      configMap:
        name: k6-scripts
        items:
          - key: 'test-merchant-apis.js'
            path: 'test-merchant-apis.js'
#  volumes:
#    - name: cache-volume
#      emptyDir:
#        medium: Memory
#        sizeLimit: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k6-scripts