apiVersion: v1
kind: Pod
metadata:
  name: vol1
spec:
#  securityContext:
#    fsGroup: 2000
  initContainers:
  - name: sleep
    image: alpine:3.16
    command: [ "sleep", "10" ]
#    args:
#      - -c
#      - >-
#        chown -R 1001:1001 /k6-script
#        sleep 5m
#      - /bin/sh
#      - -c
#      - "chown -R 1001:1001 /k6-scripts"
    volumeMounts:
      - mountPath: /k6-scripts/report
        name: k6-volume
        subPath: report
  containers:
    - image: loadimpact/k6:latest
#      securityContext:
#        runAsUser: 1001
#        runAsGroup: 2000
      name: vm1
      #      command: ["sleep", "10m"]
      command: ['k6','run',  "/k6-scripts/test-merchant-apis.js"]
#      args:
#        - run
#        - /k6-scripts/test-merchant-apis.js --out json=test.json
      volumeMounts:
        - mountPath: /k6-scripts/report
          name: k6-volume
          subPath: report
        - mountPath: /k6-scripts/test-merchant-apis.js
          name: k6-scripts
          subPath: test-merchant-apis.js
    - name: vm2
      image: nginx
      volumeMounts:
        - mountPath: /k6-scripts/report
          name: k6-volume
          subPath: report
  volumes:
    - name: k6-volume
      #      persistentVolumeClaim:
      #        claimName: test-volume
#      hostPath:
#        # 宿主上目录位置
#        path: /k6-scripts/report
#        type: DirectoryOrCreate
      emptyDir: {}
    - name: k6-scripts
      configMap:
        name: k6-scripts
        items:
          - key: 'test-merchant-apis.js'
            path: 'test-merchant-apis.js'
  restartPolicy: Never
#  backoffLimit: 0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - example-node

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: test-volume
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: my-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /k6-scripts