apiVersion: v1
kind: Pod
metadata:
  name: vol1
spec:
  containers:
    - image: alpine:3.16
      name: vm1
      command: [ "sleep", "100m" ]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
    - name: vm2
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir:
        medium: Memory
        sizeLimit: 100Mi