apiVersion: v1
kind: Pod
metadata:
  name: vol1
spec:
  containers:
    - image: alpine:3.16
      name: vm1
      command:
        - sh
        - '-c'
        - 'cp /k6-scripts/html /k6-scripts'
#      args:
#        - run
#        - /k6-scripts/html/test-merchant-apis.js
      volumeMounts:
        - mountPath: /k6-scripts
          name: cache-volume
        - mountPath: /k6-scripts/html
          name: k6-scripts
#          subPath: k6-scripts
    - name: vm2
      image: nginx
#      volumeMounts:
#        - mountPath: /usr/share/nginx/html
#          name: cache-volume
      volumeMounts:
        - mountPath: /k6-scripts
          name: cache-volume

  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: k6-scripts
      configMap:
        name: k6-scripts
        items:
          - key: 'test-merchant-apis.js'
            path: 'test-merchant-apis.js'
#  volumes:
#    - name: cache-volume
#      emptyDir:
#        medium: Memory
#        sizeLimit: 100Mi